version: '2'
services:
    web:
        build: .
        ports:
            - "8041:8041"
        volumes:
            - .:/app
        depends_on:
            - redis
    redis:
        image: redis
